<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Helpers\" />
    <Folder Include="Interfaces\" />
    <Folder Include="MappingProfiles\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Custor.Workflow.Engine.Domain\Custor.Workflow.Engine.Domain.csproj" />
  </ItemGroup>

</Project>
