<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Http" Version="3.6.0" />
    <PackageReference Include="Elsa.Server.Api" Version="2.16.0" />
    <PackageReference Include="Elsa.Workflows.Api" Version="3.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

</Project>
